[package]
name = "trileaf-lib"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
tokio = { version = "1.46.1", features = ["full"] }
reqwest = { version = "0.12.22", features = ["json"] }

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
generic-array = "1.2.0"
hex = "0.4.3"
sha2 = "0.11.0-rc.0"
